name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "* * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm ci
      - name: Update Codebending Schedule
        uses: matchai/waka-box@master
        run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 87b901869d333b234fc55eb50bd6ef68
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
